version: "3.7"
name: argent-bank-api

services:
  api:
    image: zuruh/argent-bank-api:latest
    build:
      context: .
      dockerfile: ./docker/server.dockerfile
    depends_on:
      - database
    environment:
      DATABASE_HOST: database
      DATABASE_URL: "mongodb://database:$DATABASE_PORT/$DATABASE_NAME"
    ports:
      - "$SERVER_PORT:$SERVER_PORT"

  database:
    image: mongo:5.0
    healthcheck:
      test: mongo --eval 'db.runCommand("ping").ok' localhost:27017/test --quiet
      interval: 1s
      retries: 15
      start_period: 5s
      timeout: 10s
    environment:
      MONGO_INITDB_DATABASE: $DATABASE_NAME
    ports:
      - "$DATABASE_PORT:$DATABASE_PORT"
